---
- include: packages-{{ ansible_pkg_mgr }}.yml

- name: Create Caddy user
  user: name={{ caddy_user }} system=yes createhome=yes home={{ caddy_home }}

- name: Create directories
  file: path={{ item }} state=directory owner={{ caddy_user }} mode=0770
  with_items:
    - /etc/caddy
    - /etc/ssl/caddy
    - /var/www
    - "{{ caddy_home }}"
    - /var/log/caddy

- name: Get all Caddy releases
  get_url: url=https://api.github.com/repos/mholt/caddy/git/refs/tags dest={{ caddy_home }}/releases.txt force=yes
  when: caddy_update
  register: caddy_releases_cache

- name: Set Caddy features
  copy: content="{{caddy_features}}" dest={{ caddy_home }}/features.txt
  when: caddy_update
  register: caddy_features_cache

- name: Download Caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64&features={{caddy_features}} dest={{ caddy_home }}/caddy.tar.gz force=yes
  when: caddy_releases_cache.changed or caddy_features_cache.changed
  register: caddy_binary_cache

- name: Extract Caddy
  unarchive: src={{ caddy_home }}/caddy.tar.gz dest=/usr/bin/ creates=/usr/bin/caddy copy=no
  when: caddy_binary_cache.changed

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/bin/caddy | grep cap_net_bind_service
  failed_when: False
  changed_when: False
  register: caddy_bind_cap

- name: Set capability on the binary file to be able to bind to TCP port <1024
  command: setcap cap_net_bind_service=+ep /usr/bin/caddy
  when: caddy_bind_cap.rc > 0

- name: Create Caddyfile
  copy: content="{{caddy_config}}" dest=/etc/caddy/Caddyfile
  notify: Restart Caddy

- name: Config for Upstart service from github
  get_url: url=https://raw.githubusercontent.com/mholt/caddy/master/dist/init/linux-upstart/caddy.conf dest=/etc/init/caddy.conf mode=0755
  ignore_errors: yes
  when: not caddy_init_system or caddy_init_system == "upstart"
  notify: Restart Caddy

- name: Systemd service | get config from github
  get_url: url=https://raw.githubusercontent.com/mholt/caddy/master/dist/init/linux-systemd/caddy.service dest=/etc/systemd/system/caddy.service mode=0755
  ignore_errors: yes
  when: not caddy_init_system or caddy_init_system == "systemd"
  notify: Reload systemd service file

- name: Systemd service | set ExecStart
  lineinfile: 
    state: present
    dest: /etc/systemd/system/caddy.service
    regexp: '^ExecStart\='
    line: 'ExecStart=/usr/bin/caddy -log stdout -agree=true -email {{ caddy_email }} -conf=/etc/caddy/Caddyfile -root=/var/www'
  when: not caddy_init_system or caddy_init_system == "systemd"
  notify: Reload systemd service file

# TODO enable when https://github.com/mholt/caddy/issues/821 is solved
#- name: Systemd service | set HOME
#  lineinfile: 
#    state: present
#    dest: /etc/systemd/system/caddy.service
#    regexp: '^Environment\=HOME\='
#    line: "Environment=HOME={{ caddy_home }}"
#  when: not caddy_init_system or caddy_init_system == "systemd"
#  notify: Reload systemd service file

- name: Systemd service | fix port permission error
  lineinfile: 
    state: absent
    dest: /etc/systemd/system/caddy.service
    regexp: '^NoNewPrivileges\=true'
  when: not caddy_init_system or caddy_init_system == "systemd"
  notify: Reload systemd service file

- name: Start Caddy service
  service: name=caddy state=started enabled=yes
